# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cflip < Formula
  desc "A CLI tool to switch between Claude models and providers"
  homepage "https://github.com/vanducng/cflip"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanducng/cflip/releases/download/v1.1.3/cflip_Darwin_x86_64.tar.gz"
      sha256 "0d43b9c393c26d4d17b613e8b008b0f3f2262362ff9757f1940942926884797b"

      def install
        bin.install "cflip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanducng/cflip/releases/download/v1.1.3/cflip_Darwin_arm64.tar.gz"
      sha256 "851e50fd82273a20d42a77a76a35c7e4d6d8a4fc5419a6841a5333f8b435d8e4"

      def install
        bin.install "cflip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/cflip/releases/download/v1.1.3/cflip_Linux_x86_64.tar.gz"
      sha256 "b2c8e1d4f7d9e545807ecb4b425029d7b1a7335a5ab80f214a68b5b7588c7c53"

      def install
        bin.install "cflip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/cflip/releases/download/v1.1.3/cflip_Linux_arm64.tar.gz"
      sha256 "1a0e8e7472b5b8e2c781e0f6e71a05a9eb24a6a8f00c00e97a311dc99a8d4e0c"

      def install
        bin.install "cflip"
      end
    end
  end

  test do
    system "#{bin}/cflip --version"
  end
end
