# This file was generated by GoReleaser. DO NOT EDIT.
cask "cflip" do
  name "cflip"
  desc "A CLI tool to switch between Claude models and providers"
  homepage "https://github.com/vanducng/cflip"
  version "1.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cflip"

  on_macos do
    on_intel do
      url "https://github.com/vanducng/cflip/releases/download/v#{version}/cflip_Darwin_x86_64.tar.gz"
      sha256 "29af82d0f8e90684ec310626ec6d30d470ec8088190178fe7192f88598226624"
    end
    on_arm do
      url "https://github.com/vanducng/cflip/releases/download/v#{version}/cflip_Darwin_arm64.tar.gz"
      sha256 "23f8c62e81a638d1caaf693044c2b5c1281007bef92e1173869ece488baf18bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vanducng/cflip/releases/download/v#{version}/cflip_Linux_x86_64.tar.gz"
      sha256 "7d31606b9f3c192a8209d6b3eebf4ab38f5c2c5ba0980aae11225ab79c2fb9e0"
    end
    on_arm do
      url "https://github.com/vanducng/cflip/releases/download/v#{version}/cflip_Linux_arm64.tar.gz"
      sha256 "71521b7235fbe42ab1dd0bce578e06c5147f7e2bde1947fbeedaaae0be427504"
    end
  end

  # No zap stanza required
end
