# This file was generated by GoReleaser. DO NOT EDIT.
cask "cflip" do
  name "cflip"
  desc "A CLI tool to switch between Claude models and providers"
  homepage "https://github.com/vanducng/cflip"
  version "1.6.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cflip"

  on_macos do
    on_intel do
      url "https://github.com/vanducng/cflip/releases/download/v#{version}/cflip_Darwin_x86_64.tar.gz"
      sha256 "7fa51f56df46d8fac19e5a3e94d8bd00f2d45eaebe6acf3878089fb316e5691f"
    end
    on_arm do
      url "https://github.com/vanducng/cflip/releases/download/v#{version}/cflip_Darwin_arm64.tar.gz"
      sha256 "124015ccae390c0c8918b6202a055b0f4e91bd86315fda8db34fc3152ad3678d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vanducng/cflip/releases/download/v#{version}/cflip_Linux_x86_64.tar.gz"
      sha256 "89851c1a302f583562c171631ba96bc118b6be5f2c9ec6b21aafe79b7c01fa69"
    end
    on_arm do
      url "https://github.com/vanducng/cflip/releases/download/v#{version}/cflip_Linux_arm64.tar.gz"
      sha256 "4837f7117bcbe8e2e7f94be083f9fe6d3aeeda35aa5637afccc772f41278d860"
    end
  end

  # No zap stanza required
end
