# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCli < Formula
  desc "Feature-rich interactive Jira command-line client"
  homepage "https://github.com/vanducng/jira-cli"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanducng/jira-cli/releases/download/v1.8.0/jira_1.8.0_macOS_x86_64.tar.gz"
      sha256 "aa058ef227f8d40bb71d46c2d1ed182522853602bd34be895621f5d5bd120ee9"

      define_method(:install) do
        bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanducng/jira-cli/releases/download/v1.8.0/jira_1.8.0_macOS_arm64.tar.gz"
      sha256 "3c7fae5e26e99ca087aa99ec3e6d07b6e5dacd371bb70940973f14724d30233e"

      define_method(:install) do
        bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_x86_64.tar.gz"
      sha256 "d99d157dc3922e520caba79fca9b89a36b8d2c444233c48b026a34b17306077b"
      define_method(:install) do
        bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_armv6.tar.gz"
      sha256 "d5611c32e84831087aeccdb1516cad9a93bf489acebbafe8dd9fd9e84d3bc6cf"
      define_method(:install) do
        bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_arm64.tar.gz"
      sha256 "5178245b5ae1d0e248b977bcd586ec240431a15ababcfafc19b2257e8f6be3a8"
      define_method(:install) do
        bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    help_text = shell_output("#{bin}/jira version")
    assert_includes help_text, "Version=\"#{version}\""
  end
end
