# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miucr < Formula
  desc "Owned AI code-review CLI for humans and agents"
  homepage "https://github.com/vanducng/miu-cr"
  version "0.85.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanducng/miu-cr/releases/download/v0.85.2/miucr_darwin_x86_64.tar.gz"
      sha256 "1e1df8689994aecfba0b66480eb94b13ec08077a975cd8e15b52b05eababa681"

      define_method(:install) do
        bin.install "miucr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanducng/miu-cr/releases/download/v0.85.2/miucr_darwin_arm64.tar.gz"
      sha256 "c243c759aafcc4902140a351b748dbaebe93cdc6b07dc432509c38d35f2be614"

      define_method(:install) do
        bin.install "miucr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/miu-cr/releases/download/v0.85.2/miucr_linux_x86_64.tar.gz"
      sha256 "451e1485a7b6789d826bbfc18ff3fd7be75cdb714cc1272e54cba878f0aab58c"
      define_method(:install) do
        bin.install "miucr"
      end
    end
  end

  test do
    output = shell_output("#{bin}/miucr version")
    assert_match "v#{version}", output
  end
end
