# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miudb < Formula
  desc "Headless database CLI for humans and agents"
  homepage "https://github.com/vanducng/miu-db"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanducng/miu-db/releases/download/v0.4.0/miudb_darwin_x86_64.tar.gz"
      sha256 "a5dc68ae1adfc75ce02b05945e25ca0bf6812c8897336c1138225fd17fa19347"

      define_method(:install) do
        bin.install "miudb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanducng/miu-db/releases/download/v0.4.0/miudb_darwin_arm64.tar.gz"
      sha256 "944c42e3ca0629272dedae91a99310334ff29999f31285b68c597ac6f2ec5c58"

      define_method(:install) do
        bin.install "miudb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/miu-db/releases/download/v0.4.0/miudb_linux_x86_64.tar.gz"
      sha256 "210ea8b109228b94b5a1f1f45b9ef07e6a2cae6e10ac175667dc44d14ce72281"
      define_method(:install) do
        bin.install "miudb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/miu-db/releases/download/v0.4.0/miudb_linux_arm64.tar.gz"
      sha256 "6e9002009db886db7661126a4acf7e7696da1cb3daf42bf1970d05a8e4d0c238"
      define_method(:install) do
        bin.install "miudb"
      end
    end
  end

  test do
    output = shell_output("#{bin}/miudb version --output json")
    assert_match "v#{version}", output
  end
end
