# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miudb < Formula
  desc "Headless database CLI for humans and agents"
  homepage "https://github.com/vanducng/miu-db"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanducng/miu-db/releases/download/v0.2.5/miudb_darwin_x86_64.tar.gz"
      sha256 "299e7b9461d44477e2fb5b31e8116fa65353e0d7ff05180fbae2746b24e6e618"

      define_method(:install) do
        bin.install "miudb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanducng/miu-db/releases/download/v0.2.5/miudb_darwin_arm64.tar.gz"
      sha256 "32f977f2a328a8f83a2a98ea935631cbe285d9ed35cb019c715a38639e08b552"

      define_method(:install) do
        bin.install "miudb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/miu-db/releases/download/v0.2.5/miudb_linux_x86_64.tar.gz"
      sha256 "5e0a1f4426365fa5c45e83c91a6ae05d6b14bcca04dc128555034ec33df52b61"
      define_method(:install) do
        bin.install "miudb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/miu-db/releases/download/v0.2.5/miudb_linux_arm64.tar.gz"
      sha256 "bebdca4cac5b1326b342b5470499f1a7d5dd2a5d6dfaefb39891376a5458419e"
      define_method(:install) do
        bin.install "miudb"
      end
    end
  end

  test do
    output = shell_output("#{bin}/miudb version --output json")
    assert_match "v#{version}", output
  end
end
