# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vd < Formula
  desc "CLI for vendoring and syncing Claude Code skills"
  homepage "https://github.com/vanducng/vd-cli"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanducng/vd-cli/releases/download/v2.0.1/vd_darwin_x86_64.tar.gz"
      sha256 "c6bbf2e07e1f16a74186903a89881d74026c88a14d1a3907c12da59aac365381"

      define_method(:install) do
        bin.install "vd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanducng/vd-cli/releases/download/v2.0.1/vd_darwin_arm64.tar.gz"
      sha256 "c17fedd3987259909165b3f0d2a388c716b658b31699374bfa15a1edb63fda20"

      define_method(:install) do
        bin.install "vd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/vd-cli/releases/download/v2.0.1/vd_linux_x86_64.tar.gz"
      sha256 "c5716bd432d07e970f54fdafbd16e9b72782a40f773dc28bb475cb7edb3d9202"
      define_method(:install) do
        bin.install "vd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/vd-cli/releases/download/v2.0.1/vd_linux_arm64.tar.gz"
      sha256 "57cd644a9aacbdafccb4780baeb8eed014d61509128944197b9d77a336cd5ea5"
      define_method(:install) do
        bin.install "vd"
      end
    end
  end

  test do
    system "#{bin}/vd", "--version"
  end
end
