# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vd < Formula
  desc "Vendoring package manager for coding-agent skills (Claude Code, Codex)"
  homepage "https://github.com/vanducng/vd-cli"
  version "3.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanducng/vd-cli/releases/download/v3.4.1/vd_darwin_x86_64.tar.gz"
      sha256 "ce1df2df3526b9eac34c69dacc91ecd341db53faed55bf95997d7be60a5f0c3c"

      define_method(:install) do
        bin.install "vd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanducng/vd-cli/releases/download/v3.4.1/vd_darwin_arm64.tar.gz"
      sha256 "5d841d31802ec0bdc281cc8e345235b18449b93a27d503980330cc5c3d7ce967"

      define_method(:install) do
        bin.install "vd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/vd-cli/releases/download/v3.4.1/vd_linux_x86_64.tar.gz"
      sha256 "bee12d5000a9c25983bc0db4d0e362700649e1a7ec80501267efe358cdce82f2"
      define_method(:install) do
        bin.install "vd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanducng/vd-cli/releases/download/v3.4.1/vd_linux_arm64.tar.gz"
      sha256 "a240f0e7d5af715363a1bfdb09225d11d2ff908f65bb353196162bb3dd3c1728"
      define_method(:install) do
        bin.install "vd"
      end
    end
  end

  test do
    system "#{bin}/vd", "--version"
  end
end
